providers = ["php", "node"]

[variables]
NIXPACKS_NO_MIGRATE = "1"
NIXPACKS_LARAVEL_MIGRATE = "0"
NIXPACKS_LARAVEL_SKIP_MIGRATIONS = "1"

[phases.setup]
nixPkgs = ["php84", "php84Packages.composer", "nodejs_20", "nginx"]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader --no-interaction",
  "npm install",
  "npm run build",
  "php artisan config:cache --no-interaction",
  "php artisan route:cache --no-interaction",
  "php artisan view:cache --no-interaction",
  "php artisan storage:link"
]

[start]
cmd = "php artisan migrate --force && php-fpm -D && nginx -g 'daemon off;'"
